export const theme = {
  colors: {
    PRIMARY: '#007bff',
    PRIMARY_BACKGROUND: '#524e4e',
    DANGER: '#f72f2f',
    BACKGROUND_LIGHT: '#fff',
    BACKGROUND_DARK: '#1c1c1c',
    CARD_DARK: '#1a1a1a',
    TEXT_LIGHT: '#333',
    TEXT_DARK: '#fff',
    TEXT_SECONDARY_LIGHT: '#666',
    TEXT_SECONDARY_DARK: '#aaa',
    BORDER_LIGHT: '#ccc',
    BORDER_DARK: '#272727',
    MODAL_BACKGROUND_LIGHT: '#f9f9f9',
    MODAL_BACKGROUND_DARK: '#121212',
    MAP_BUTTON: '#e0e0e0',
    NOTIFICATION: '#ff6347',
    ATTACHMENT_TEXT_LIGHT: '#333',
    ATTACHMENT_TEXT_DARK: '#fff',
    TASK_ITEM_BACKGROUND_LIGHT: '#f9f9f9',
    TASK_ITEM_BACKGROUND_DARK: '#1c1c1c',
    LOCATION_TEXT_LIGHT: '#888',
    LOCATION_TEXT_DARK: '#bbb',
    DESCRIPTION_TEXT_DARK: '#ddd',
    INPUT_TEXT: '#000',
  },
  fontSizes: {
    SMALL: 12,
    MEDIUM: 14,
    EXTRA_MEDIUM: 16,
    LARGE: 18,
    EXTRA_LARGE: 20,
  },
  padding: {
    SMALL: 8,
    MEDIUM: 12,
    LARGE: 16,
  },
  margin: {
    TINY: 4,
    SMALL: 8,
    MEDIUM: 10,
    LARGE: 16,
  },
  borderRadius: {
    SMALL: 8,
  },
  borderWidth: {
    THIN: 1,
  },
  gap: {
    SMALL: 8,
  },
};
